-- newpack -- poses de pareja (Shared) importadas de newpack/.
-- Ya revisadas: van a la categoria normal de emotes compartidos, sin
-- categoria propia en el menu.

local ENABLED = true -- ponlo en false para desactivar el pack
if not ENABLED then return end

---@type AnimationListConfig
---@diagnostic disable-next-line: missing-fields
local CustomDP = {}

CustomDP.Shared = {
    ["kiss17"] = {
        "genesismods_kissme@kissmale9",
        "kissmale9",
        "Kiss 9(Male)",
        "kiss18",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.35,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["kiss18"] = {
        "genesismods_kissme@kissfemale9",
        "kissfemale9",
        "Kiss 9(Female)",
        "kiss17",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["kiss19"] = {
        "genesismods_kissme@kissmale10",
        "kissmale10",
        "Kiss 10(Male)",
        "kiss20",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.38,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["kiss20"] = {
        "genesismods_kissme@kissfemale10",
        "kissfemale10",
        "Kiss 10(Female)",
        "kiss19",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["kiss5"] = {
        "tigerle@custom@couple@kissing1a",
        "tigerle_couple_kissing1a",
        "Kiss 5",
        "kiss6",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["kiss6"] = {
        "tigerle@custom@couple@kissing1b",
        "tigerle_couple_kissing1b",
        "Kiss 6",
        "kiss5",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.0,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["kiss7"] = {
        "tigerle@custom@couple@kissing2a",
        "tigerle_couple_kissing2a",
        "Kiss 7",
        "kiss8",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["kiss8"] = {
        "tigerle@custom@couple@kissing2b",
        "tigerle_couple_kissing2b",
        "Kiss 8",
        "kiss7",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.0,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["cuddleet"] = {
        "tigerle@custom@couple@cuddle1a",
        "tigerle_couple_cuddle1a",
        "Cuddle A",
        "cuddleet2",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["cuddleet2"] = {
        "tigerle@custom@couple@cuddle1b",
        "tigerle_couple_cuddle1b",
        "Cuddle B",
        "cuddleet",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.0,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["cuddleet3"] = {
        "tigerle@custom@couple@cuddle@no2a",
        "tigerle_couple_cuddleno2a",
        "Cuddle 2 A",
        "cuddleet4",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["cuddleet4"] = {
        "tigerle@custom@couple@cuddle@no2b",
        "tigerle_couple_cuddleno2b",
        "Cuddle 2 B",
        "cuddleet3",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.0,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["layying"] = {
        "tigerle@custom@couple@laying1a",
        "tigerle_couple_laying1a",
        "Laying Together A",
        "layying2",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["layying2"] = {
        "tigerle@custom@couple@laying1b",
        "tigerle_couple_laying1b",
        "Laying Together B",
        "layying",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.0,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["sitting"] = {
        "tigerle@custom@couple@sittingonbench@no1a",
        "tigerle_couple_sittingonbench_no1a",
        "Sit On Bench A",
        "sitting2",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["sitting2"] = {
        "tigerle@custom@couple@sittingonbench@no1b",
        "tigerle_couple_sittingonbench_no1b",
        "Sit On Bench B",
        "sitting",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.0,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["cuddleet5"] = {
        "tigerle@custom@couple@standcuddle_a",
        "tigerle_couple_standcuddle_a",
        "Stand Cuddle A",
        "cuddleet6",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["cuddleet6"] = {
        "tigerle@custom@couple@standcuddle_b",
        "tigerle_couple_standcuddle_b",
        "Stand Cuddle B",
        "cuddleet5",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.0,
            yPos = 0.35,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 180.0,
        }
    },
    ["standingg"] = {
        "tigerle@custom@couple@standing_a",
        "tigerle_couple_standing_a",
        "Standing Together A",
        "standingg2",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["standingg2"] = {
        "tigerle@custom@couple@standing_b",
        "tigerle_couple_standing_b",
        "Standing Together B",
        "standingg",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.10,
            yPos = 0.30,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["bfff"] = {
        "tigerle@custom@pose@bff1a",
        "tigerle_pose_bff1a",
        "BFF Pose A",
        "bfff2",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        }
    },
    ["bfff2"] = {
        "tigerle@custom@pose@bff1b",
        "tigerle_pose_bff1b",
        "BFF Pose B",
        "bfff",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            xPos = 0.70,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        }
    },
    ["sitchairposem"] = {
        "myu@fm_couple1_1",
        "fm_couple1_f_clip",
        "Sit Chair Pose NEW (Male)",
        "sitchairposef",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Prop = 'hei_heist_stn_chairstrip_01',
            PropBone = 0,
            PropPlacement = {
                -0.0400,
                -0.120,
                -0.600,
                -180.0000,
                -180.0000,
                9.0999,
            },
        },
    },
    ["sitchairposef"] = {
        "myu@fm_couple1_2",
        "fm_couple1_m_clip",
        "Sit Chair Pose NEW (Female)",
        "sitchairposem",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.0,
            yPos = 1.2,
            zPos = 0.35,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0
        },
    },
    ["sitloveposem"] = {
        "couplemale@sarahdiehexe",
        "couplemale_clip",
        "Sit Love Pose NEW (Male)",
        "sitloveposef",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["sitloveposef"] = {
        "couplefemale@sarahdiehexe",
        "couplefemale_clip",
        "Sit Love Pose NEW (Female)",
        "sitloveposem",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = -0.31,
            yPos = 0.35,
            zPos = 0.09,
            xRot = -2.99,
            yRot = 0.0,
            zRot = 290.0,
        },
    },
    ["sidebysm"] = {
        "banner_01@sharror",
        "banner_01_clip",
        "Side By Side Pose NEW (Male)",
        "sidebysf",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["sidebysf"] = {
        "banner_02@sharror",
        "banner_02_clip",
        "Side By Side Pose NEW (Female)",
        "sidebysm",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.48,
            yPos = -0.1,
            zPos = 0.0,
            xRot = 2.0,
            yRot = 0.0,
            zRot = 0.0,
        },
    },
    ["sitchrlv2m"] = {
        "benchm@spider",
        "benchm_clip",
        "Sit Chair Love2 NEW (Male)",
        "sitchrlv2f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["sitchrlv2f"] = {
        "benchf@spider",
        "benchf_clip",
        "Sit Chair Love2 NEW (Female)",
        "sitchrlv2m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.0,
            yPos = 0.39,
            zPos = 0.36,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        },
    },
    ["sitloverockm"] = {
        "chocoholic@couple46",
        "couple46_clip",
        "Sit Love Rock NEW (Male)",
        "sitloverockf",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["sitloverockf"] = {
        "chocoholic@couple45",
        "couple45_clip",
        "Sit Love Rock NEW (Female)",
        "sitloverockm",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.17,
            yPos = 0.35,
            zPos = 0.15,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 30.0,
        },
    },
    ["kisslovpose1m"] = {
        "chocoholic@couple51",
        "couple51_clip",
        "Kissing Love1 NEW (Male)",
        "kisslovpose1f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["kisslovpose1f"] = {
        "chocoholic@couple52",
        "couple52_clip",
        "Kissing Love1 NEW (Female)",
        "kisslovpose1m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.0,
            yPos = 0.30,
            zPos = -0.1,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 180.0,
        },
    },
    ["lovewalkpose3m"] = {
        "chocoholic@couple57",
        "couple57_clip",
        "Love Walking Pose 3 NEW (Male)",
        "lovewalkpose3f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["lovewalkpose3f"] = {
        "chocoholic@couple58",
        "couple58_clip",
        "Love Walking Pose 3 NEW (Female)",
        "lovewalkpose3m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = -0.98,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        },
    },
    ["sitlovepose6m"] = {
        "schoko7@sharror",
        "schoko7_clip",
        "Sit Love Pose 6 NEW (Male)",
        "sitlovepose6f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["sitlovepose6f"] = {
        "schoko8@sharror",
        "schoko8_clip",
        "Sit Love Pose 6 NEW (Female)",
        "sitlovepose6m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.0,
            yPos = 0.0,
            zPos = 0.7,
            xRot = -7.0,
            yRot = 0.0,
            zRot = 0.0,
        },
    },
    ["sitlovepose7m"] = {
        "couplem4@spider",
        "couplem4_clip",
        "Sit Love Pose 7 NEW (Male)",
        "sitlovepose7f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            bone = 0,
            zPos = -5.0,
        },
    },
    ["sitlovepose7f"] = {
        "couple4@spider",
        "couple4_clip",
        "Sit Love Pose 7 NEW (Female)",
        "sitlovepose7m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.0,
            yPos = 0.55,
            zPos = 0.38,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        },
    },
    ["wallocepose2m"] = {
        "couple_wall_01@sharror",
        "couple_wall_01_clip",
        "Wall Love Pose 2 NEW (Male)",
        "wallocepose2f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["wallocepose2f"] = {
        "couple_wall_02@sharror",
        "couple_wall_02_clip",
        "Wall Love Pose 2 NEW (Female)",
        "wallocepose2m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.82,
            yPos = -0.21,
            zPos = 0.03,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 180.0,
        },
    },
    ["sitlovepose8m"] = {
        "couplebench_m@gengaranimation",
        "couplebench_m_clip",
        "Sit Love Pose 8 NEW (Male)",
        "sitlovepose8f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["sitlovepose8f"] = {
        "couplebench_f@gengaranimation",
        "couplebench_f_clip",
        "Sit Love Pose 8 NEW (Female)",
        "sitlovepose8m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = -1.45,
            yPos = 0.81,
            zPos = 0.35,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        },
    },
    ["sitlovepose9m"] = {
        "anim@male_couple_01",
        "m_couple_01_clip",
        "Sit Love Pose 9 NEW (Male)",
        "sitlovepose9f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["sitlovepose9f"] = {
        "anim@female_couple_01",
        "f_couple_01_clip",
        "Sit Love Pose 9 NEW (Female)",
        "sitlovepose9m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.0,
            yPos = 0.47,
            zPos = 0.8,
            xRot = -15.0,
            yRot = 0.0,
            zRot = 0.0,
        },
    },
    ["lovepose4m"] = {
        "anim@male_couple_02",
        "m_couple_02_clip",
        "Love Pose 4 NEW (Male)",
        "lovepose4f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["lovepose4f"] = {
        "anim@female_couple_02",
        "f_couple_02_clip",
        "Love Pose 4 NEW (Female)",
        "lovepose4m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = -0.5,
            yPos = 0.0,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 0.0,
        },
    },
    ["lovepose8m"] = {
        "anim@male_couple_03_b",
        "m_couple_03_b_clip",
        "Love Pose 8 NEW (Male)",
        "lovepose8f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["lovepose8f"] = {
        "anim@female_couple_03_b",
        "f_couple_03_b_clip",
        "Love Pose 8 NEW (Female)",
        "lovepose8m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = 0.0,
            yPos = 0.13,
            zPos = 0.0,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 95.0,
        },
    },
    ["lovepose22m"] = {
        "couplemale_leancar@joker",
        "couplemale_leancar_clip",
        "Love Pose 21 NEW (Male)",
        "lovepose22f",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
        },
    },
    ["lovepose22f"] = {
        "couplefemale_leancar@joker",
        "couplefemale_leancar_clip",
        "Love Pose 21 NEW (Female)",
        "lovepose22m",
        AnimationOptions = {
            EmoteMoving = false,
            EmoteLoop = true,
            Attachto = true,
            bone = 0,
            xPos = -0.2,
            yPos = 0.32,
            zPos = 0.1,
            xRot = 0.0,
            yRot = 0.0,
            zRot = 180.0,
        },
    },
}

RegisterAddonEmotes(CustomDP)
